### PR TITLE
Add a Travis CI build configuration

### PR DESCRIPTION
**Pull request by TimMoore**

### CODE REVIEW

**Comment by TimMoore** [comment]
@rasummer running `gulp bundle` is triggering errors from the `lint:js` task. How do you normally build this project?

**Comment by rasummer** [comment]
@TimMoore I use `gulp bundle:pack`

**Comment by TimMoore** [comment]
Thanks, @rasummer. With that change, the basic build works. You can see the results here: https://travis-ci.com/lightbend/antora-ui-lightbend-theme/builds/120103676

I added the link checker in another commit, and it does pick up some broken links: https://travis-ci.com/lightbend/antora-ui-lightbend-theme/builds/120104063

```
page not found from 404.html to xyz/6.0/index.html
page not found from index.html to building-shopping-cart.html
page not found from index.html to setting-up-postgresql.html
page not found from index.html to setting-up-kafka.html
page not found from index.html to configuring-akka-cluster.html
anchor not found from 404.html to 404.html#
anchor not found from index.html to index.html#
page not found from index.html to ../6.0/index.html
could not fetch external page: Error: Moved Permanently (Code: 301) from index.html to https://developer.lightbend.com/docs/telemetry/latest/home.html
could not fetch external page: Error: Moved Permanently (Code: 301) from index.html to https://developer.lightbend.com/docs/fortify/latest/
could not fetch external page: Error: See Other (Code: 303) from index.html to https://www.playframework.com/documentation
could not fetch external page: Error: Moved Permanently (Code: 301) from index.html to http://www.scala-sbt.org/documentation.html
could not fetch external page: Error: See Other (Code: 303) from index.html to https://portal.lightbend.com/
```

- The redirects should probably be updated. Even though they'll load correctly in a real browser, it's better to link directly to the destination and avoid the extra requests.
- The other ones seem to be false positives for test data. We could exclude them from the check using a regex, but maybe it's simpler to fix them in the source. WDYT?

**Comment by rasummer** [comment]
@TimMoore agree let's fix the redirects. 

The false positives, yep I think there are just part of the test data of the UI theme. 

Probably won't get to this until tomorrow of the next day. In the middle of rolling out LB banners on project sites. Therefore if you need this out sooner, please feel free to jump in.

best Rich

**Comment by TimMoore** [comment]
No urgency from my perspective, but I can fix the links.

**Comment by TimMoore** [comment]
I updated a few links, but there were some that didn't make sense to change:

- https://www.playframework.com/documentation redirects to https://www.playframework.com/documentation/2.7.x/Home, but we don't want to have to update this theme whenever there is a new Play release
- https://portal.lightbend.com/ redirects to https://portal.lightbend.com/account/login if you aren't authenticated, which the link checker is not. For logged in users, it loads directly.

So I added a flag allowing for a URL to redirect (once) without an error.

There were also two other URL patterns that I didn't want to change, so I configured the link checker to ignore them instead:

- `ui-model.yml` contains a component called "xyz"... I'm not sure exactly why so I didn't want to mess with it.
- Menu headers have `href="#"`, and the link checker didn't like those, but in an actual browser, they're handled with JavaScript.

**Pull request merged**
