### PR TITLE
See akka serverless branding

### PR DESCRIPTION
**Pull request by katsutoxin**
issue: https://github.com/lightbend/cloudstatemachine/issues/1836

- change logo lightbend-cloudstate-reverse.svg  to akka serverless icon
- Use the Akka blue colors, not the Lightbend orange, when Akka Serverless is the brand

The screenshot of **cloudstate-private.html**
Screen Shot 2020-10-14 at 4 14 37 PM

Hi @rstento,

I have a question: 
1. 
I just want to make the change to docs.lbcs.dev    , but based on source code, look like my PR  to change color to "akka blue" impacts files
- public/cloudstate-private.html   (for dev docs:  docs.lbcs.dev )
- public/cloudstate.html  (for prod docs:  docs.cloudstate.com )
- public/index.html  (I don't know this is for what)

I would like to check with you what is the proper way to do it.  Or we can only deploy to docs.lbcs.dev and not deploy to prod?

### CODE REVIEW

**Comment by katsutoxin** [comment]
I changed to color 'akka-blue' in https://www.lightbend.com/brand/akka#logo

Here is the screenshot

Screen Shot 2020-10-14 at 11 02 53 PM

**Comment by katsutoxin** [comment]
add @michaelpnash in the loop.

**Review by rstento — COMMENTED** [review]
Sorry @katsutoxin, I didn't read this carefully enough. Don't worry about making any changes to the documentation theme. Richard is working on a set of new themes for the OSS and commercial documentation. It will include search and will be branded as requested by Marketing.

**Comment by katsutoxin** [comment]
> Sorry @katsutoxin, I didn't read this carefully enough. Don't worry about making any changes to the documentation theme. Richard is working on a set of new themes for the OSS and commercial documentation. It will include search and will be branded as requested by Marketing.

Hi @rstento , in the task https://github.com/lightbend/cloudstatemachine/issues/1836  It also requires the document context change (for example, replace  "Lightbend Cloudstate" with "Akka Serverless") , do you mind also change the docs context in repo https://github.com/lightbend/cloudstate-docs  ?

Thanks !
Danny

**Comment by katsutoxin** [comment]
@rasummer is working on this with search feature.  So close this PR.

**Pull request closed without merging**
