### PR TITLE
update canonical to use attributes

### PR DESCRIPTION
**Pull request by rasummer**
@rstento you should now be able to use the following in the head of .adoc pages

`:page-canonicalUrl: https://www.your-url.com`

It might only work in production, in development it doesn't show up for me, but that's the same with some of the other attributes that also use native page vars. Let's push it to production to test.

### CODE REVIEW

**Comment by rstento** [comment]
Merging to try it.

**Comment by rstento** [comment]
Hi Rich,

I can't get it to work. I even tried using the --fetch on the command line
to make sure Antora was fetching the latest ui zip. I've posted a question
on the antora gitter channel. Hopefully, I'll hear something soon.


Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by rasummer** [comment]
One other thought, is there a place you can set it such as the site yaml file for the specific page, as opposed to setting it in the .adoc file.

**Comment by rstento** [comment]
No, because the site.yml file sets it for the whole site, there isn't a way
to separate it by source.

Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by rstento** [comment]
I just read in the antora doc how to create a noindex directive that will
be output in the sitemap.xml file. This should be an alternative solution,
because all of the pages I'm sharing are under a subfolder. I'm just not
sure whether google automatically reads the sitemaps automatically or if it
has to be configured somewhere on Techhub to make google read them?

Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by rstento** [comment]
Sorry, it's not in the sitemap. Instead, Antora will generate a robots.txt
file, but again I have the same question of whether a robots.txt in the
root of the doc dir will be read by google, or if it has to be configured
onTechhub

Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by rasummer** [comment]
There is a file here: https://developer.lightbend.com/robots.txt

**Comment by rasummer** [comment]
And this looks like the place to edit it: https://github.com/lightbend/techhub-landing-page/blob/master/src/main/paradox/robots.txt

**Comment by rstento** [comment]
Perfect, I think that is a much simpler solution. Thanks!

Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Pull request merged**
